spring.application.name=IT211_Ss18_btth3

spring.datasource.url=jdbc:h2:mem:ss18_btth3_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=thangnguyen260704

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true